## 实现一维卷积和二维卷积

将使用numpy实现 最后调用torch对比结果

In [1]:
# 使用相关库
import torch
import torch.nn.functional as F
import numpy as np
from utils import ss_conv1d, ss_conv2d

定义输入

In [2]:
# 输入
inp_1d = np.array([1, 2, 3, 4, 5])
inp_2d = np.array([[1, 2, 3, 4, 5],
                   [2, 3, 4, 5, 6],
                   [3, 4, 5, 6, 7],
                   [4, 5, 6, 7, 8],
                   [5, 6, 7, 8, 9]])
# 卷积核
kernel_1d = np.array([1, 1, 0])
kernel_2d = np.array([[1, 1, 1],
                      [0, 0, 0],
                      [0, 0, 0]])

调用utils中实现的conv1d，conv2d

In [3]:
out_1d = ss_conv1d(inp_1d, kernel_1d)
out_2d = ss_conv2d(inp_2d, kernel_2d)  
print(out_1d)
print(out_2d)

[1. 3. 5. 7. 9. 5. 0.]
[[ 1.  3.  6.  9. 12.  9.  5.]
 [ 2.  5.  9. 12. 15. 11.  6.]
 [ 3.  7. 12. 15. 18. 13.  7.]
 [ 4.  9. 15. 18. 21. 15.  8.]
 [ 5. 11. 18. 21. 24. 17.  9.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


调用torch中的卷积方法

需要注意torch的卷积方法期望的输入格式为[batch, channel, L, W]，卷积核与此对应

1d: 步长为1
> 输入：[B = 1, C = 1, L = 5] 
>
> 卷积核：[B = 1, C = 1, L = 3]
>
> 输出：[B = 1, C = 1, L = 3]

2d: 步长为1
> 输入：[B = 1, C = 1, L = 5, W = 5] 
>
> 卷积核：[B = 1, C = 1, L = 3, W = 3]
>
> 输出：[B = 1, C = 1, L = 3, W = 3]

In [12]:
torch_inp_1d = torch.tensor(inp_1d).view(1, 1, -1)   # [1, 1, 5]
torch_kernel_1d = torch.tensor(kernel_1d).view(1, 1, -1) # [1, 1, 3]
torch_inp_2d = torch.tensor(inp_2d).unsqueeze(0)   # [1, 1, 5, 5]
torch_kernel_2d = torch.tensor(kernel_2d).view(1, 1, 3, -1) # [1, 1, 3, 3]
torch_out_1d = F.conv1d(torch_inp_1d, torch_kernel_1d.flip(2), stride=1, padding=kernel_1d.shape[0]-1)
torch_out_2d = F.conv2d(torch_inp_2d, torch_kernel_2d.flip([2, 3]), stride=(1, 1), padding=(kernel_2d.shape[0]-1, kernel_2d.shape[1]-1))
print(torch_out_1d)
print(torch_out_2d)

tensor([[[1, 3, 5, 7, 9, 5, 0]]])
tensor([[[ 1,  3,  6,  9, 12,  9,  5],
         [ 2,  5,  9, 12, 15, 11,  6],
         [ 3,  7, 12, 15, 18, 13,  7],
         [ 4,  9, 15, 18, 21, 15,  8],
         [ 5, 11, 18, 21, 24, 17,  9],
         [ 0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0]]])
